### PR TITLE
fix model reference

### PR DESCRIPTION
**Pull request by fhdk**
https://github.com/linuxmint/mintstick/issues/75

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, the fix works fine, but I'm not really enthusiastic about the other commits.

We're generally against changing code just for formatting reasons (spaces, tabs, etc..), as it has a big impact on git history - for instance, instead of being able to easily tell where a particular line change came from, you hit the format commit and have to start over.  The variable renaming is a bit excessive also.

In this case, this is not a massively complex program, so it's not as big a deal, and it does improve readability quite a bit (no one likes horizontal scrollbars when editing code :)).

Just keep this in mind in any future contributions.

Can you squash all the formatting commits into one?  Then I'll merge.  Thanks

**Comment by fhdk** [comment]
Thank you for considering the changes.
I will remember your advise.

I have squashed the commits as requested

**Comment by mtwebster** [comment]
Hmm it doesn't look like you updated anything here - did you forget to push back to github?

**Comment by mtwebster** [comment]
I squashed and merged these manually, closing this:

https://github.com/linuxmint/mintstick/commit/7f0f03e9e8940b39204c3e839cf5c80e132a5139
https://github.com/linuxmint/mintstick/commit/a0920e78250050f55f6953b018ce76bc24f3d812

Thanks

**Pull request closed without merging**
